#baseurl      = "https://jakub-pazio.github.io/Page/"
baseurl = "https://jakubpazio.xyz"
title = "my part of internet"
languageCode = "en-us"
theme = "digitalgarden"
pagination.pagerSize = 10

[params]
dateform = "Jan 2, 2006"
dateformShort = "Jan 2"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"
enableSearch = true

# Metadata mostly used in document's head
description = "My new homepage or blog"
keywords = "homepage, blog"
images = [""]

[taxonomies]
category = "blog"
tag = "tags"
series = "series"

[languages]
[languages.en]
title = "🐲"
keywords = ""
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
readOtherPosts = "Read other posts"

# And you can even create generic menu
[[menu.main]]
weight = 1
name = "Index"
url = "/"


[[menu.main]]
weight = 2
name = "Blog"
url = "/articles"
